### ISSUE TITLE
Upgrade process fails with ENOENT

### ISSUE THREAD

**Issue by g2p** [rpm-software-management/dnf-plugin-system-upgrade#18]
After dnf reboot, the system boots twice without installing anything, I have the following logs:

```
sept. 24 14:19:16 Fedora dnf[232]: [Errno 2] No such file or directory
sept. 24 14:19:16 Fedora systemd[1]: dnf-system-upgrade.service: main process exited, code=exited, status=1/FAILURE
```

This is from an up-to-date Fedora 22.
It's a fairly small VM, maybe some implicit dependencies are missing?

**Comment by wgwoods** [comment]
...I'd need to see a lot more logs to have any idea what's going on there. Maybe look at `/var/log/dnf.log`? If there's nothing helpful there, you could add `-d9` to the `ExecStart=` line in `/lib/systemd/system/dnf-system-upgrade.service` (to turn up DNF's debugging output) and try it again...

Also, what versions of dnf-plugin-system-upgrade / dnf / PackageKit are installed?

**Comment by g2p** [comment]
Ah, thanks for telling me about dnf.log. Apparently it's because there's no Plymouth.

```
Sep 24 20:05:59 INFO --- logging initialized ---
Sep 24 20:05:59 DDEBUG timer: config: 16 ms
Sep 24 20:05:59 DEBUG cachedir: /var/cache/dnf
Sep 24 20:05:59 DEBUG Loaded plugins: kickstart, copr, playground, system-upgrade, generate_completion_cache, needs-restarting, config-manager, debuginfo-install, Query, reposync, protected_packages, noroot, migrate, download, builddep
Sep 24 20:05:59 DEBUG DNF version: 1.1.1
Sep 24 20:05:59 DEBUG_2 Command: dnf --releasever=23 system-upgrade upgrade 
Sep 24 20:05:59 DEBUG_2 Installroot: /
Sep 24 20:05:59 DEBUG_2 Releasever: 23
Sep 24 20:05:59 DEBUG_2 Base command: system-upgrade
Sep 24 20:05:59 DEBUG_2 Extra commands: [u'upgrade']
Sep 24 20:05:59 DEBUG_2 timer: sack setup: 3 ms
Sep 24 20:05:59 DEBUG_4 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 136, in _main
    cli.run()
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1085, in run
    return self.command.run(self.base.extcmds)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 270, in run
    self._call_sub("run", extcmds)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 278, in _call_sub
    subfunc(*args)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 379, in run_upgrade
    Plymouth.set_mode("updates")
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 157, in set_mode
    return self._plymouth("change-mode", "--" + mode)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 146, in _plymouth
    self.alive = (call((PLYMOUTH, cmd) + args) == 0)
  File "/usr/lib64/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] Aucun fichier ou dossier de ce type
Sep 24 20:05:59 CRITICAL [Errno 2] Aucun fichier ou dossier de ce type
Sep 24 20:05:59 DEBUG_2 Cleaning up.
```

I have
- dnf-1.1.1-2.fc22.noarch
- dnf-plugin-system-upgrade-0.4.1-1.fc22.noarch
- PackageKit-glib-1.0.8-2.fc22.x86_64

**Comment by g2p** [comment]
The upgrade worked with Plymouth installed. By the way, I wish DNF shared the rpm cache instead of letting its downloads get wiped.

**Comment by wgwoods** [comment]
> The upgrade worked with Plymouth installed.

Good to know - I'll see about fixing this in a minute.

> By the way, I wish DNF shared the rpm cache instead of letting its downloads get wiped.

DNF and this plugin _do_ share their package/metadata cache, mostly. Except it seems that DNF 1.1 moves the location of its package cache and/or deletes any RPMs left in the cache if you perform any other operation (see issue #5).

Oh, and the next version of the `dnf-plugin-system-upgrade` package should correctly migrate `fedup`'s package cache if it's present; see commit 72b9b1c61cb3939d19bf10833d3216f17edefbeb.

**Comment by g2p** [comment]
Thanks!
