### ISSUE TITLE
Can't load plugin in f22 with Chinese locale

### ISSUE THREAD

**Issue by hizukiayaka** [rpm-software-management/dnf-plugin-system-upgrade#32]
Hi, my language environment is zh_CN.utf8, with using the latest version 0.7.0-1 in dnf
I will got
Traceback (most recent call last):
  File "/bin/dnf", line 36, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 198, in user_main
    errcode = main(args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 84, in main
    return _main(base, args)
  File "/usr/lib/python2.7/site-packages/dnf/cli/main.py", line 117, in _main
    cli.configure(map(ucd, args))
  File "/usr/lib/python2.7/site-packages/dnf/cli/cli.py", line 1006, in configure
    self.base.plugins.run_init(self.base, self)
  File "/usr/lib/python2.7/site-packages/dnf/plugin.py", line 104, in run_init
    plugin = p_cls(base, cli)
  File "/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py", line 359, in __init__
    super(SystemUpgradePlugin, self).**init**(base, cli)
TypeError: must be type, not None

But if I use the LANG=C, it would work

**Comment by kparal** [comment]
Reported here in Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1278031

**Comment by kparal** [comment]
Another traceback related to Chinese locale:

```
Nov 04 21:04:21 ERROR 加载插件失败：system_upgrade
Nov 04 21:04:21 SUBDEBUG
Traceback (most recent call last):
File “/usr/lib/python2.7/site-packages/dnf/plugin.py”, line 124, in import_modules
module = importlib.import_module(name)
File “/usr/lib64/python2.7/importlib/init.py”, line 37, in import_module
import(name)
File “/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py”, line 363, in
class SystemUpgradeCommand(dnf.cli.Command):
File “/usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py”, line 369, in SystemUpgradeCommand
_(“OPTIONS”), _(“VERSION”))
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xe9 in position 0: ordinal not in range(128)
```

The user says:

> I comment off the line 368 and 368 in /usr/lib/python2.7/site-packages/dnf-plugins/system_upgrade.py
> ,then the problem is solved and my os updates to fedora 23 successfully

https://fedoramagazine.org/upgrading-from-fedora-22-to-fedora-23/#comment-449918

**Comment by yol** [comment]
Also affects ja_JP.utf8 and de_DE.utf8, so possibly all languages which use more than 7-bit ASCII characters.

**Comment by wgwoods** [comment]
It looks like (at least part of) this is a problem in upstream DNF - see rpm-software-management/dnf#375 for more info.

PR #34 _technically_ fixes the problem but since `dnf.i18n.ucd*` are being deprecated I'm inclined to _try_ to find a solution that doesn't rely on that.

**Comment by xasx** [comment]
It is also here
https://bugzilla.redhat.com/show_bug.cgi?id=1277895
