### ISSUE TITLE
obsolete fedup-dracut-plymouth.noarch too.

### ISSUE THREAD

**Issue by sergiomb2** [rpm-software-management/dnf-plugin-system-upgrade#46]
After upgrade my system, dnf list extras show that fedup-dracut-plymouth was not deleted, I think that also should be obsoleted by dnf-plugin-system-upgrade

Thanks

**Comment by wgwoods** [comment]
dnf has code to handle these kinds of problems. Try `dnf list extras` to find packages which no longer exist in the active repos, for example.

There's no _need_ for us to forcibly remove this package for your system, and I'd rather not have to push out another update just to remove this for you, so.. I'm going to decline. But a future package maintainer could do this, if they felt like it.

**Comment by keszybz** [comment]
It seems good style to obsolete the package if we know for certain that it is now useless. Users often don't know what a certain package does exactly, and would be afraid to remove it for fear of breaking something. At some point the old package might block some upgrade through dependencies; best to avoid that.

No need to push out update just for this, it can go out whenever there's an update for other reasons.
