### ISSUE TITLE
Branches and versions on Zanata

### ISSUE THREAD

**Issue by piotrdrag** [rpm-software-management/dnf-plugin-system-upgrade#8]
Currently there is a Zanata "version" for every release [1]. I know it might be counter-intuitive, but "version" should correspond to a branch, not a release. So, in the case of dnf-plugin-system-upgrade, there should be only one "version", master.

[1] https://fedora.zanata.org/project/view/dnf-plugin-system-upgrade/versions

**Comment by wgwoods** [comment]
Ah, okay. So it's alright to have string changes within a "version"?

**Comment by piotrdrag** [comment]
Yes, as long as you have "versions" for different branches. If you have any branches in git (for F23, F24 etc.), that is.
